print("What is Cryptography?")
print("According to the Merriam Webster dictionary, cryptography is,")
print("the enciphering and deciphering of messages in secret code or cipher; also : the computerized encoding and decoding of information.")
input("Press enter to continue.")
print("")
print("What this means is it converts some form of data into a format, or protocol,")
print("unreadable for someone who doesn’t have the protocol.")
input("Press enter to continue.")
print("")
print("This makes it useful for keeping data uncompromised during transit and storage.")
input("Press enter to continue.")
print("")
print("Although cryptography dates back to 5th century Egypt (and earlier),")
print("computers have heralded breakthroughs in both cryptographic methods and methods to crack cryptographic codes.")
input("Press enter to continue.")
print("")
print("Because computers run through so much data so incredibly quickly, ")
print("they can create extremely strong encryption protocols and crack extremely strong protocols too.")
input("Press enter to continue.")
print("")
print("Sources")
input("Press enter to continue.")
print("")
print('"Cryptography." Merriam-Webster.com. Merriam-Webster, n.d. Web. 5 Sept. 2018. ')
input("Press enter to continue.")
print("")
print('"Cryptography." Hosted by Melvyn Bragg. In Our Time, hosted by Melvyn Bragg, BBC, 29 Jan. 2004. BBC, www.bbc.co.uk/programmes/p004y272. Accessed 5 Sept. 2018.')
input("Press enter to continue.")
print("")
print('"Cryptography." Techopedia, 2018, www.techopedia.com/definition/1770/cryptography. Accessed 5 Sept. 2018. ')
input("Press enter to continue.")
print("")
print('"Cryptography." Wikipedia, Wikimedia Foundation, 29 Aug. 2018, en.wikipedia.org/wiki/Cryptography. Accessed 5 Sept. 2018. ')
input("Press enter to continue.")
print("")
print('Peshin, Akash. "What Is Cryptography?" ScienceABC, Science ABC, 2018, www.scienceabc.com/innovation/what-is-cryptography.html. Accessed 5 Sept. 2018. ')
input("Press enter to end.")
print("")
